### ISSUE TITLE
TODO: markdown 

### ISSUE THREAD

**Issue by BogdanaOst** [BogdanaOst/First_Task_For_Binary#1]
>  markdown для читабельності не буде лишнім

**Comment by volodymyr-kushnir** [comment]
@BogdanaOst і справді — нє, не буде. А ще можна глянути пару [**лайфхаків і підказок**](https://github.com/volodymyr-kushnir/agenda).

**Comment by BogdanaOst** [comment]
@volodymyr-kushnir оце так поворот :smile: Дякую:)

**Comment by BogdanaOst** [comment]
@volodymyr-kushnir а що стосовно Pull Requests? Треба їх заюзати в домашці?

**Comment by volodymyr-kushnir** [comment]
@BogdanaOst ммм, взагалі-то бажано. В умові завдання так то нічого про то не сказано, але хитрий **git**-овець знає, що якщо не пушнути наверх кілька гілок і не змерджити вже наверху через **Pull Request**, а натомість зробити `git merge` локально, а вже тоді `git push` — то локальні гілки не будуть мати апстріму (--set-upstream), відтак не будуть віддані наверх і тому наверху всі комміти будуть виглядати так, ніби вони були зроблені в одній і тій же гілці. Пам-пам.

**Comment by BogdanaOst** [comment]
@volodymyr-kushnir ще раз дякую)
